//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FosterAndFreeman.RecoverCompanionApplication.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FosterAndFreeman.RecoverCompanionApplication.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting Connection.
        /// </summary>
        public static string AttemptingConnection {
            get {
                return ResourceManager.GetString("AttemptingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Logs.
        /// </summary>
        public static string AuditLogs {
            get {
                return ResourceManager.GetString("AuditLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage 1 Heater Deviation:.
        /// </summary>
        public static string BaseHeaterDeviation {
            get {
                return ResourceManager.GetString("BaseHeaterDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Target.
        /// </summary>
        public static string BaseTarget {
            get {
                return ResourceManager.GetString("BaseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string CaseOperator {
            get {
                return ResourceManager.GetString("CaseOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference:.
        /// </summary>
        public static string CaseReference {
            get {
                return ResourceManager.GetString("CaseReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging.
        /// </summary>
        public static string ChamberBreakSeal {
            get {
                return ResourceManager.GetString("ChamberBreakSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditioning.
        /// </summary>
        public static string ChamberConditioning {
            get {
                return ResourceManager.GetString("ChamberConditioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling.
        /// </summary>
        public static string ChamberCooling {
            get {
                return ResourceManager.GetString("ChamberCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating.
        /// </summary>
        public static string ChamberHeat {
            get {
                return ResourceManager.GetString("ChamberHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation.
        /// </summary>
        public static string ChamberInitialisation {
            get {
                return ResourceManager.GetString("ChamberInitialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamber Type:.
        /// </summary>
        public static string ChamberType {
            get {
                return ResourceManager.GetString("ChamberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you certain you want to delete this log?.
        /// </summary>
        public static string ConfirmDeleteLog {
            get {
                return ResourceManager.GetString("ConfirmDeleteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you certain that you want to program the currently connected device?.
        /// </summary>
        public static string ConfirmProgram {
            get {
                return ResourceManager.GetString("ConfirmProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: These changes cannot be undone..
        /// </summary>
        public static string ConfirmWriteExtraData {
            get {
                return ResourceManager.GetString("ConfirmWriteExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Successful.
        /// </summary>
        public static string ConnectionSuccesful {
            get {
                return ResourceManager.GetString("ConnectionSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper Based.
        /// </summary>
        public static string CopperBased {
            get {
                return ResourceManager.GetString("CopperBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Service Pack.
        /// </summary>
        public static string CreateServicePack {
            get {
                return ResourceManager.GetString("CreateServicePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Service Pack...
        ///This may take a few minutes..
        /// </summary>
        public static string CreatingServicePack {
            get {
                return ResourceManager.GetString("CreatingServicePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOP-R1.
        /// </summary>
        public static string DevelopR1 {
            get {
                return ResourceManager.GetString("DevelopR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOP-R2.
        /// </summary>
        public static string DevelopR2 {
            get {
                return ResourceManager.GetString("DevelopR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOP-R3.
        /// </summary>
        public static string DevelopR3 {
            get {
                return ResourceManager.GetString("DevelopR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVELOP-R4.
        /// </summary>
        public static string DevelopR4 {
            get {
                return ResourceManager.GetString("DevelopR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop-R Type:.
        /// </summary>
        public static string DevelopRType {
            get {
                return ResourceManager.GetString("DevelopRType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the case reference and operator below..
        /// </summary>
        public static string EnterExtraInformation {
            get {
                return ResourceManager.GetString("EnterExtraInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Serial Number of Device:.
        /// </summary>
        public static string EnterSerial {
            get {
                return ResourceManager.GetString("EnterSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All.
        /// </summary>
        public static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Connection:
        ///{0}.
        /// </summary>
        public static string FailedConnection {
            get {
                return ResourceManager.GetString("FailedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Log Headers.
        /// </summary>
        public static string FetchingLogHeaders {
            get {
                return ResourceManager.GetString("FetchingLogHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Mode.
        /// </summary>
        public static string FileMode {
            get {
                return ResourceManager.GetString("FileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Programming!.
        /// </summary>
        public static string FinishedProgramming {
            get {
                return ResourceManager.GetString("FinishedProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware:.
        /// </summary>
        public static string Firmware {
            get {
                return ResourceManager.GetString("Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Firmware Erasing.
        /// </summary>
        public static string FirmwareErasing {
            get {
                return ResourceManager.GetString("FirmwareErasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Finished.
        /// </summary>
        public static string FirmwareFinished {
            get {
                return ResourceManager.GetString("FirmwareFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update Initialising.
        /// </summary>
        public static string FirmwareInititalise {
            get {
                return ResourceManager.GetString("FirmwareInititalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Firmware Updating.
        /// </summary>
        public static string FirmwareUpdating {
            get {
                return ResourceManager.GetString("FirmwareUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version:.
        /// </summary>
        public static string FirmwareVersion {
            get {
                return ResourceManager.GetString("FirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuming Time(Minutes):.
        /// </summary>
        public static string HeatMinutes {
            get {
                return ResourceManager.GetString("HeatMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialising.
        /// </summary>
        public static string Initialising {
            get {
                return ResourceManager.GetString("Initialising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        public static string InputPath {
            get {
                return ResourceManager.GetString("InputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Erase Finished Key.
        /// </summary>
        public static string InvalidEraseFinishedKey {
            get {
                return ResourceManager.GetString("InvalidEraseFinishedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Erase Started Key.
        /// </summary>
        public static string InvalidEraseStartedKey {
            get {
                return ResourceManager.GetString("InvalidEraseStartedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Read Receipt.
        /// </summary>
        public static string InvalidReadReceipt {
            get {
                return ResourceManager.GetString("InvalidReadReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Serial Number entered was invalid. Please enter a valid serial number..
        /// </summary>
        public static string InvalidSerialNumber {
            get {
                return ResourceManager.GetString("InvalidSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Chamber.
        /// </summary>
        public static string LargeChamber {
            get {
                return ResourceManager.GetString("LargeChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Test 1 Result:.
        /// </summary>
        public static string LeakTest1Result {
            get {
                return ResourceManager.GetString("LeakTest1Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak Test 2 Result:.
        /// </summary>
        public static string LeakTest2Result {
            get {
                return ResourceManager.GetString("LeakTest2Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal Type:.
        /// </summary>
        public static string MetalType {
            get {
                return ResourceManager.GetString("MetalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Selected.
        /// </summary>
        public static string NoDataSelected {
            get {
                return ResourceManager.GetString("NoDataSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data to write file was found.
        /// </summary>
        public static string NoDataToWrite {
            get {
                return ResourceManager.GetString("NoDataToWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Devices Found.
        /// </summary>
        public static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Logs Found.
        /// </summary>
        public static string NoLogsFound {
            get {
                return ResourceManager.GetString("NoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precusor.
        /// </summary>
        public static string Precursor {
            get {
                return ResourceManager.GetString("Precursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage 2 Heater Deviation:.
        /// </summary>
        public static string PrecursorHeaterDeviation {
            get {
                return ResourceManager.GetString("PrecursorHeaterDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursor Target.
        /// </summary>
        public static string PrecursorTarget {
            get {
                return ResourceManager.GetString("PrecursorTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Deviation:.
        /// </summary>
        public static string PressureDeviation {
            get {
                return ResourceManager.GetString("PressureDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Target.
        /// </summary>
        public static string PressureTarget {
            get {
                return ResourceManager.GetString("PressureTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Finished.
        /// </summary>
        public static string PrintingFinished {
            get {
                return ResourceManager.GetString("PrintingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing in progress....
        /// </summary>
        public static string PrintingInProgress {
            get {
                return ResourceManager.GetString("PrintingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Device.
        /// </summary>
        public static string ProgramDevice {
            get {
                return ResourceManager.GetString("ProgramDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditioning Time(Minutes):.
        /// </summary>
        public static string PumpdownMinutes {
            get {
                return ResourceManager.GetString("PumpdownMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generated.
        /// </summary>
        public static string ReportGenerated {
            get {
                return ResourceManager.GetString("ReportGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Audit logs to print:.
        /// </summary>
        public static string SelectAuditLogstoPrint {
            get {
                return ResourceManager.GetString("SelectAuditLogstoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number:.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Pack Created!.
        /// </summary>
        public static string ServicePackCreated {
            get {
                return ResourceManager.GetString("ServicePackCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Pack Creation Cancelled!.
        /// </summary>
        public static string ServicePackCreatingCancelled {
            get {
                return ResourceManager.GetString("ServicePackCreatingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Graphs.
        /// </summary>
        public static string ShowGraphs {
            get {
                return ResourceManager.GetString("ShowGraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Coloured.
        /// </summary>
        public static string SilverColoured {
            get {
                return ResourceManager.GetString("SilverColoured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Companion Application is already open. Unable to open multiple instances.
        /// </summary>
        public static string SingleInstanceError {
            get {
                return ResourceManager.GetString("SingleInstanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Single Page Per Log.
        /// </summary>
        public static string SinglePageMode {
            get {
                return ResourceManager.GetString("SinglePageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Chamber.
        /// </summary>
        public static string SmallChamber {
            get {
                return ResourceManager.GetString("SmallChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software:.
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time: .
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully exported all logs..
        /// </summary>
        public static string SuccesfullyExportedAll {
            get {
                return ResourceManager.GetString("SuccesfullyExportedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string TestFail {
            get {
                return ResourceManager.GetString("TestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string TestSuccess {
            get {
                return ResourceManager.GetString("TestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These changes are permanent and may not be edited later..
        /// </summary>
        public static string ThisCannotBeUndone {
            get {
                return ResourceManager.GetString("ThisCannotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover was unable to enter PC Mode. Please try again later..
        /// </summary>
        public static string UnableToEnterPCMode {
            get {
                return ResourceManager.GetString("UnableToEnterPCMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Enumerate Devices.
        /// </summary>
        public static string UnableToEnumerateDevices {
            get {
                return ResourceManager.GetString("UnableToEnumerateDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Fetch Devices.
        /// </summary>
        public static string UnableToFetchDevices {
            get {
                return ResourceManager.GetString("UnableToFetchDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate report..
        /// </summary>
        public static string UnableToGenerateReport {
            get {
                return ResourceManager.GetString("UnableToGenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Open Device.
        /// </summary>
        public static string UnableToOpenDevice {
            get {
                return ResourceManager.GetString("UnableToOpenDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the file right now. Please try again later..
        /// </summary>
        public static string UnableToOpenFileRightNow {
            get {
                return ResourceManager.GetString("UnableToOpenFileRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck All.
        /// </summary>
        public static string UncheckAll {
            get {
                return ResourceManager.GetString("UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Software.
        /// </summary>
        public static string UpdateSoftware {
            get {
                return ResourceManager.GetString("UpdateSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Mode.
        /// </summary>
        public static string USBMode {
            get {
                return ResourceManager.GetString("USBMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
